words:
  - Attributify
  - Ayaka
  - bumpp
  - catppuccin
  - changelogithub
  - defu
  - devicon
  - frommd
  - iconify
  - macchiato
  - Neko
  - nekw
  - nolyfill
  - ofetch
  - onnx
  - pkgroll
  - safetensors
  - Shaderr
  - sizecheck
  - splitpanes
  - taze
  - tomd
  - unocss
  - unplugin
  - velin
  - vueuse
